// Niveles de la sección de Robótica — Aprende con Ana Isabella
// Robot: posiciones [fila, columna]; dir 0 arriba, 1 derecha, 2 abajo, 3 izquierda.
//   "reto" = bloques de la mejor solución (3 estrellas); "maxBloques" obliga a
//   usar la idea nueva del nivel. Varios tableros = el mismo programa debe
//   funcionar en todos (para eso sirven los sensores).
// Circuitos: cada pieza tiene "rot" (giro inicial) y "sol" (giro de la
//   solución pensada). Los interruptores tienen "cerrado" y "solCerrado".

const NIVELES_ROBOT = [
  {
    titulo: "Avanzar y girar",
    bloques: ["avanzar", "izq", "der"],
    reto: 7,
    texto: "Los robots de verdad no saben qué es arriba o abajo: solo saben <strong>avanzar</strong> hacia donde miran y <strong>girar</strong>. Fíjate hacia dónde apunta la flecha del robot y llévalo a la estrella.",
    tableros: [{ filas: 6, cols: 6, robot: { f: 5, c: 0, dir: 0 }, estrellas: [[2, 3]], rocas: [] }],
  },
  {
    titulo: "Repetir",
    bloques: ["avanzar", "izq", "der", "repetir"],
    reto: 2,
    maxBloques: 3,
    texto: "¡Qué flojera poner 5 veces Avanzar! Usa <strong>Repetir</strong>: todo lo que pongas adentro se hace las veces que digas. Toca Repetir y después Avanzar para ponerlo adentro.",
    tableros: [{ filas: 6, cols: 6, robot: { f: 2, c: 0, dir: 1 }, estrellas: [[2, 5]], rocas: [] }],
  },
  {
    titulo: "La escalera",
    bloques: ["avanzar", "izq", "der", "repetir"],
    reto: 5,
    maxBloques: 6,
    texto: "Sube la escalera hasta la estrella. Pista: todos los escalones son iguales… ¡repite uno!",
    tableros: [{
      filas: 6, cols: 6, robot: { f: 5, c: 0, dir: 0 }, estrellas: [[1, 4]],
      rocas: [[5, 1], [4, 2], [3, 3], [2, 4], [3, 0], [2, 1], [1, 2], [0, 3]],
    }],
  },
  {
    titulo: "El cuadrado",
    bloques: ["avanzar", "izq", "der", "repetir"],
    reto: 4,
    maxBloques: 6,
    texto: "Recoge las 3 estrellas. Pista de ingeniera: ¡puedes poner un <strong>Repetir adentro de otro Repetir</strong>!",
    tableros: [{
      filas: 6, cols: 6, robot: { f: 4, c: 1, dir: 0 }, estrellas: [[1, 1], [1, 4], [4, 4]],
      rocas: [[2, 2], [2, 3], [3, 2], [3, 3]],
    }],
  },
  {
    titulo: "Repetir hasta llegar",
    bloques: ["avanzar", "izq", "der", "hasta"],
    reto: 2,
    maxBloques: 2,
    texto: "Ahora el robot va a probar tu programa en <strong>3 tableros distintos</strong> y tiene que funcionar en todos. Como no sabes cuántos pasos son (¡y solo caben 2 bloques!), usa <strong>Repetir hasta llegar</strong>: el robot sigue hasta encontrar la estrella.",
    tableros: [
      { filas: 6, cols: 6, robot: { f: 2, c: 0, dir: 1 }, estrellas: [[2, 3]], rocas: [] },
      { filas: 6, cols: 6, robot: { f: 2, c: 0, dir: 1 }, estrellas: [[2, 5]], rocas: [] },
      { filas: 6, cols: 6, robot: { f: 2, c: 0, dir: 1 }, estrellas: [[2, 1]], rocas: [] },
    ],
  },
  {
    titulo: "El sensor",
    bloques: ["avanzar", "izq", "der", "hasta", "si"],
    reto: 4,
    maxBloques: 5,
    texto: "Los robots tienen <strong>sensores</strong> para saber qué hay enfrente. Usa <strong>Si hay algo adelante</strong>: si hay una roca o la orilla, gira; si no, avanza. ¡Un solo programa para los 3 tableros!",
    tableros: [
      { filas: 6, cols: 6, robot: { f: 5, c: 0, dir: 0 }, estrellas: [[0, 5]], rocas: [] },
      { filas: 6, cols: 6, robot: { f: 5, c: 0, dir: 0 }, estrellas: [[3, 4]], rocas: [[2, 0]] },
      { filas: 6, cols: 6, robot: { f: 5, c: 2, dir: 0 }, estrellas: [[2, 5]], rocas: [[1, 2]] },
    ],
  },
  {
    titulo: "Laberintos",
    bloques: ["avanzar", "izq", "der", "repetir", "hasta", "si"],
    reto: 4,
    maxBloques: 6,
    texto: "Estos laberintos son más difíciles… ¿funcionará tu programa del sensor? ¡Así trabajan las aspiradoras robot: no conocen la casa, pero reaccionan a lo que sienten!",
    tableros: [
      { filas: 6, cols: 6, robot: { f: 5, c: 0, dir: 0 }, estrellas: [[5, 5]], rocas: [] },
      { filas: 6, cols: 6, robot: { f: 5, c: 1, dir: 0 }, estrellas: [[4, 3]], rocas: [[1, 1], [2, 4]] },
      { filas: 6, cols: 6, robot: { f: 4, c: 0, dir: 1 }, estrellas: [[5, 0]], rocas: [[4, 3]] },
    ],
  },
];

const NIVELES_CIRCUITO = [
  {
    titulo: "Prende el foco",
    filas: 3, cols: 3, objetivo: ["foco"],
    texto: "Un <strong>circuito</strong> es un camino cerrado: la electricidad sale de la batería por el <strong>+</strong>, pasa por el foco y regresa por el <strong>−</strong>. Toca los cables para girarlos y cierra el camino.",
    piezas: [
      { f: 0, c: 0, tipo: "curva", rot: 0, sol: 1 },
      { f: 0, c: 1, tipo: "recta", rot: 0, sol: 1 },
      { f: 0, c: 2, tipo: "curva", rot: 2, sol: 2 },
      { f: 1, c: 0, tipo: "bateria", rot: 0 },
      { f: 1, c: 2, tipo: "foco", id: "foco", rot: 0 },
      { f: 2, c: 0, tipo: "curva", rot: 0, sol: 0 },
      { f: 2, c: 1, tipo: "recta", rot: 1, sol: 1 },
      { f: 2, c: 2, tipo: "curva", rot: 2, sol: 3 },
    ],
  },
  {
    titulo: "El interruptor",
    filas: 3, cols: 4, objetivo: ["foco"],
    texto: "El <strong>interruptor</strong> es una puerta para la electricidad: abierto corta el camino y cerrado la deja pasar. Arregla los cables y ciérralo tocándolo.",
    piezas: [
      { f: 0, c: 0, tipo: "curva", rot: 1, sol: 1 },
      { f: 0, c: 1, tipo: "recta", rot: 1, sol: 1 },
      { f: 0, c: 2, tipo: "interruptor", rot: 1, cerrado: false, solCerrado: true },
      { f: 0, c: 3, tipo: "curva", rot: 1, sol: 2 },
      { f: 1, c: 0, tipo: "bateria", rot: 0 },
      { f: 1, c: 3, tipo: "foco", id: "foco", rot: 0 },
      { f: 2, c: 0, tipo: "curva", rot: 0, sol: 0 },
      { f: 2, c: 1, tipo: "recta", rot: 1, sol: 1 },
      { f: 2, c: 2, tipo: "recta", rot: 0, sol: 1 },
      { f: 2, c: 3, tipo: "curva", rot: 3, sol: 3 },
    ],
  },
  {
    titulo: "El motor",
    filas: 4, cols: 4, objetivo: ["motor"],
    texto: "Los <strong>motores</strong> hacen girar las ruedas y los brazos de los robots. Conecta el motor para que su hélice gire.",
    piezas: [
      { f: 0, c: 0, tipo: "curva", rot: 1, sol: 1 },
      { f: 0, c: 1, tipo: "recta", rot: 0, sol: 1 },
      { f: 0, c: 2, tipo: "recta", rot: 1, sol: 1 },
      { f: 0, c: 3, tipo: "curva", rot: 1, sol: 2 },
      { f: 1, c: 0, tipo: "recta", rot: 1, sol: 0 },
      { f: 1, c: 3, tipo: "motor", id: "motor", rot: 0 },
      { f: 2, c: 0, tipo: "bateria", rot: 0 },
      { f: 2, c: 3, tipo: "recta", rot: 0, sol: 0 },
      { f: 3, c: 0, tipo: "curva", rot: 0, sol: 0 },
      { f: 3, c: 1, tipo: "recta", rot: 1, sol: 1 },
      { f: 3, c: 2, tipo: "recta", rot: 0, sol: 1 },
      { f: 3, c: 3, tipo: "curva", rot: 2, sol: 3 },
    ],
  },
  {
    titulo: "Focos en serie",
    filas: 3, cols: 4, objetivo: ["focoA", "focoB"],
    texto: "Dos focos <strong>en serie</strong>: la electricidad pasa primero por uno y después por el otro, en un solo camino. ¡Prende los dos!",
    piezas: [
      { f: 0, c: 0, tipo: "curva", rot: 0, sol: 1 },
      { f: 0, c: 1, tipo: "foco", id: "focoA", rot: 1 },
      { f: 0, c: 2, tipo: "foco", id: "focoB", rot: 1 },
      { f: 0, c: 3, tipo: "curva", rot: 2, sol: 2 },
      { f: 1, c: 0, tipo: "bateria", rot: 0 },
      { f: 1, c: 3, tipo: "recta", rot: 1, sol: 0 },
      { f: 2, c: 0, tipo: "curva", rot: 0, sol: 0 },
      { f: 2, c: 1, tipo: "recta", rot: 0, sol: 1 },
      { f: 2, c: 2, tipo: "recta", rot: 1, sol: 1 },
      { f: 2, c: 3, tipo: "curva", rot: 1, sol: 3 },
    ],
  },
  {
    titulo: "Focos en paralelo",
    filas: 3, cols: 4, objetivo: ["focoA", "focoB"],
    texto: "Dos focos <strong>en paralelo</strong>: cada uno tiene su propio camino. Los cables en forma de <strong>T</strong> reparten la electricidad. Si un foco se apaga, ¡el otro sigue prendido!",
    piezas: [
      { f: 0, c: 0, tipo: "curva", rot: 1, sol: 1 },
      { f: 0, c: 1, tipo: "recta", rot: 1, sol: 1 },
      { f: 0, c: 2, tipo: "t", rot: 0, sol: 2 },
      { f: 0, c: 3, tipo: "curva", rot: 2, sol: 2 },
      { f: 1, c: 0, tipo: "bateria", rot: 0 },
      { f: 1, c: 2, tipo: "foco", id: "focoA", rot: 0 },
      { f: 1, c: 3, tipo: "foco", id: "focoB", rot: 0 },
      { f: 2, c: 0, tipo: "curva", rot: 0, sol: 0 },
      { f: 2, c: 1, tipo: "recta", rot: 1, sol: 1 },
      { f: 2, c: 2, tipo: "t", rot: 2, sol: 0 },
      { f: 2, c: 3, tipo: "curva", rot: 2, sol: 3 },
    ],
  },
  {
    titulo: "¡Cortocircuito!",
    filas: 3, cols: 4, objetivo: ["foco"],
    texto: "¡Ups! Este circuito tiene un <strong>cortocircuito</strong>: la electricidad se va por el camino fácil (los cables de la derecha) y no pasa por el foco. Así el foco no prende y la batería se calienta. ¡Corta ese camino!",
    piezas: [
      { f: 0, c: 0, tipo: "curva", rot: 1 },
      { f: 0, c: 1, tipo: "recta", rot: 1 },
      { f: 0, c: 2, tipo: "t", rot: 2 },
      { f: 0, c: 3, tipo: "curva", rot: 2 },
      { f: 1, c: 0, tipo: "bateria", rot: 0 },
      { f: 1, c: 2, tipo: "foco", id: "foco", rot: 0 },
      { f: 1, c: 3, tipo: "recta", rot: 0, sol: 1 },
      { f: 2, c: 0, tipo: "curva", rot: 0 },
      { f: 2, c: 1, tipo: "recta", rot: 1 },
      { f: 2, c: 2, tipo: "t", rot: 0 },
      { f: 2, c: 3, tipo: "curva", rot: 3 },
    ],
  },
  {
    titulo: "El circuito del robot",
    filas: 4, cols: 5, objetivo: ["ojos", "ruedas"],
    texto: "¡El gran final! Arma el circuito de un robot: sus <strong>ojos</strong> (el foco) y sus <strong>ruedas</strong> (el motor), con un interruptor para prenderlo.",
    piezas: [
      { f: 0, c: 0, tipo: "curva", rot: 1, sol: 1 },
      { f: 0, c: 1, tipo: "interruptor", rot: 1, cerrado: false, solCerrado: true },
      { f: 0, c: 2, tipo: "recta", rot: 0, sol: 1 },
      { f: 0, c: 3, tipo: "t", rot: 1, sol: 2 },
      { f: 0, c: 4, tipo: "curva", rot: 2, sol: 2 },
      { f: 1, c: 0, tipo: "recta", rot: 1, sol: 0 },
      { f: 1, c: 3, tipo: "foco", id: "ojos", rot: 0 },
      { f: 1, c: 4, tipo: "motor", id: "ruedas", rot: 0 },
      { f: 2, c: 0, tipo: "bateria", rot: 0 },
      { f: 2, c: 3, tipo: "recta", rot: 1, sol: 0 },
      { f: 2, c: 4, tipo: "recta", rot: 1, sol: 0 },
      { f: 3, c: 0, tipo: "curva", rot: 0, sol: 0 },
      { f: 3, c: 1, tipo: "recta", rot: 1, sol: 1 },
      { f: 3, c: 2, tipo: "recta", rot: 1, sol: 1 },
      { f: 3, c: 3, tipo: "t", rot: 3, sol: 0 },
      { f: 3, c: 4, tipo: "curva", rot: 1, sol: 3 },
    ],
  },
];

if (typeof module !== "undefined") module.exports = { NIVELES_ROBOT, NIVELES_CIRCUITO };
